### ISSUE TITLE
Change the master branch to "main" branch.

### ISSUE THREAD

**Issue by omenking** [100DaysOfCloud/100DaysOfCloudApp#1]
We need to change then name to improve the overall efficiency of our application.

**Comment by rishabkumar7** [comment]
- [ ] branch.
- Create a branch named "main".
- Made "main" as default 
- Delete "master" branch.

**Comment by rishabkumar7** [comment]
![image](https://user-images.githubusercontent.com/45825464/87348190-54c55580-c522-11ea-80e8-4048579185fb.png)
