### ISSUE TITLE
Rework PR #22 due to incorrect merge

### ISSUE THREAD

**Issue by antoniolofiego** [100DaysOfCloud/100DaysOfCloudApp#26]
As of right now, there are outstanding issues in #22 that need to be addressed as soon as possible. 

Please refer to this code review for changes required:
https://github.com/100DaysOfCloud/100DaysOfCloudBackend/pull/22#issuecomment-663915820

**Comment by antoniolofiego** [comment]
Closed with #28

**Comment by syedautherabbas** [comment]
@antoniolofiego  had to retain env var in dynamo Db as tests were failing without it. by default, AWS_REGION is passed to the Lambda for the region of the Lambda so it won't matter.  Dont need to add __main__ as we are using pytest to run tests so did not add those.
